/** 与 RealtimePanel className 字段对应 */
const styles = {
  mainPanel: 'bizpack-device-details-panel',
  modalHeader: 'bizpack-device-details-modalHeader',
  modalTitle: 'bizpack-device-details-modalTitle',
  titleIcon: 'bizpack-device-details-titleIcon',
  titleText: 'bizpack-device-details-titleText',
  closeBtn: 'bizpack-device-details-closeBtn',
  closeIcon: 'bizpack-device-details-closeIcon',
  headerDivider: 'bizpack-device-details-headerDivider',
  panelBody: 'bizpack-device-details-panelBody',
  deviceNameBar: 'bizpack-device-details-deviceNameBar',
  deviceNameLabel: 'bizpack-device-details-deviceNameLabel',
  deviceNameValue: 'bizpack-device-details-deviceNameValue',
  infoRow: 'bizpack-device-details-infoRow',
  infoItem: 'bizpack-device-details-infoItem',
  infoLabel: 'bizpack-device-details-infoLabel',
  infoValue: 'bizpack-device-details-infoValue',
  sectionTitle: 'bizpack-device-details-sectionTitle',
  sectionIcon: 'bizpack-device-details-sectionIcon',
  sectionText: 'bizpack-device-details-sectionText',
  metricRow: 'bizpack-device-details-metricRow',
  metricCard: 'bizpack-device-details-metricCard',
  metricCardActive: 'bizpack-device-details-metricCardActive',
  metricLabel: 'bizpack-device-details-metricLabel',
  metricMain: 'bizpack-device-details-metricMain',
  metricValue: 'bizpack-device-details-metricValue',
  metricUnit: 'bizpack-device-details-metricUnit',
  emptyWrap: 'bizpack-device-details-emptyWrap',
  trendSectionTitle: 'bizpack-device-details-sectionTitle',
  trendChart: 'bizpack-device-details-trendChart',
  chartWrap: 'bizpack-device-details-chartWrap',
};

export default styles;
